#!/usr/bin/env python3
"""
Run whenever you edit index.html:
  python3 make_html_gz.py
Writes html_gz.h into the same directory.
"""
import gzip, sys, os

src = sys.argv[1] if len(sys.argv) > 1 else "index.html"
dst = os.path.join(os.path.dirname(src), "html_gz.h")

raw = open(src, "rb").read()
gz  = gzip.compress(raw, compresslevel=9)
print(f"{src}: {len(raw):,} → {len(gz):,} bytes ({len(gz)/len(raw)*100:.0f}%)")

lines = [
  "// Auto-generated by make_html_gz.py — do not edit.",
  "#pragma once", "#include <pgmspace.h>", "",
  f"const uint16_t HTML_GZ_LEN = {len(gz)};", "",
  "const uint8_t HTML_GZ[] PROGMEM = {",
]
row = []
for b in gz:
    row.append(f"0x{b:02x}")
    if len(row) == 16: lines.append("  " + ",".join(row) + ","); row = []
if row: lines.append("  " + ",".join(row))
lines.append("};")
open(dst, "w").write("\n".join(lines) + "\n")
print(f"Written: {dst}")
